#!/bin/sh

uci set system.@system[0].timezone=WIB-7
uci set system.@system[0].zonename=Asia/Jakarta
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

echo 'chain mangle_postrouting_ttl65 {' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '  type filter hook postrouting priority 300; policy accept;' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '  counter ip ttl set 65' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '}' >> /etc/nftables.d/10-custom-filter-chains.nft

echo 'chain mangle_prerouting_ttl65 {' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '  type filter hook prerouting priority 300; policy accept;' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '  counter ip ttl set 65' >> /etc/nftables.d/10-custom-filter-chains.nft
echo '}' >> /etc/nftables.d/10-custom-filter-chains.nft

sed -i 's#mirrors.vsean.net#downloads.immortalwrt.org#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
sed -i 's/ImmortalWrt/boluOS/g' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R24.6.12'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='boluOS '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
